version: 1.2
workflows:
   - name: plink2_bed2vcf
     subclass: WDL
     primaryDescriptorPath: /plink2_bed2vcf.wdl
     testParameterFiles:
         - /plink2_bed2vcf.json
   - name: plink2_vcf2bed
     subclass: WDL
     primaryDescriptorPath: /plink2_vcf2bed.wdl
     testParameterFiles:
         - /plink2_vcf2bed.json
   - name: plink2_vcf2pgen
     subclass: WDL
     primaryDescriptorPath: /plink2_vcf2pgen.wdl
     testParameterFiles:
         - /plink2_vcf2pgen.json
   - name: liftover_vcf
     subclass: WDL
     primaryDescriptorPath: /liftover_vcf_picard.wdl
     testParameterFiles:
         - /liftover_vcf_picard.json
