version: 1.2
workflows:
   - name: plink2_bed2vcf
     subclass: WDL
     primaryDescriptorPath: /plink2_bed2vcf.wdl
     testParameterFiles:
         - /plink2_bed2vcf.json
   - name: convert_build
     subclass: WDL
     primaryDescriptorPath: /convert_build.wdl
     testParameterFiles:
         - /convert_build.json
